server:
    port: 8082
spring:
    datasource:
        url: jdbc:h2:mem:saga-orchestration;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
    application:
        name: PaymentService

logging:
    structured:
        format:
            console: logstash
            file: logstash
        json:
            stacktrace:
                root: first
                max-length: 1024
                include-common-frames: true
                include-hashes: true