server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:mem:saga-orchestration;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
    application:
        name: OrderService
    cloud:
        function:
            definition: supplier;consumer
        stream:
            bindings:
                supplier-out-0:
                    destination: order-created
                consumer-in-0:
                    destination: order-updated
            kafka:
                binder: 
                    brokers: localhost:9092
                
logging:
    structured:
        format:
            console: logstash
            file: logstash
        json:
            stacktrace:
                root: first
                max-length: 1024
                include-common-frames: true
                include-hashes: true