server:
    port: 8083
spring:
    datasource:
        url: jdbc:h2:mem:saga-orchestration;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
    application:
        name: OrderOrchestration
    cloud:
        function:
            definition: processor
        stream:
            bindings:
                processor-out-0:
                    destination: order-updated
                processor-in-0:
                    destination: order-created
            kafka:
                binder: 
                    brokers: localhost:9092

service:
    endpoints:
        inventory: http://localhost:8081
        payment: http://localhost:8082

                
logging:
    structured:
        format:
            console: logstash
            file: logstash
        json:
            stacktrace:
                root: first
                max-length: 1024
                include-common-frames: true
                include-hashes: true